# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7862fe721bd29cd58e9db86d69d3faee09c62cd68e3e3319b54b8134fdfd4e1440cfe4c78773002badb9c13867211ca589e08a3ef689b29a364e6101133fb5d5

test:
  secret_key_base: 5952412d7a860f662c162f5b438a1282b259696396d8c1e135e1ef0b00012ced135f84f6e26ff5b1f13502bc892d28434a9a181a88fdc7711a74673a0ba06844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
